apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "flask-role"
        vault.hashicorp.com/agent-inject-secret-api-key: "secret/data/flask-config"
        vault.hashicorp.com/agent-inject-template-api-key: |
          {{- with secret "secret/data/flask-config" -}}
          export WEATHER_API_KEY="{{ .Data.data.API_KEY }}"
          {{- end }}
        vault.hashicorp.com/tls-skip-verify: "true" 
    spec:
      serviceAccountName: flask-service-account
      containers:
        - name: flask-container
          image: dubithal/flask-app:latest
          ports:
            - containerPort: 5000
