apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

